spring.application.name=server

spring.datasource.url=jdbc:mysql://localhost:3306/nutri_progress_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.token.secret=${JWT_TOKEN_SECRET}
jwt.token.access.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.token.refresh.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_BIOGURT}
spring.mail.password=${SENHA_LD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true