FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

RUN apk add --no-cache curl bash

COPY pom.xml .
COPY .mvn/ .mvn/
COPY mvnw .
RUN chmod +x mvnw && \
    ./mvnw dependency:go-offline -B --no-transfer-progress

COPY src ./src

EXPOSE 8080 5005

CMD ["./mvnw", "spring-boot:run", \
     "-Dspring-boot.run.profiles=dev", \
     "-Dspring-boot.run.jvmArguments=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005"]
